from enum import Enum

class SchemaSource(str, Enum):
    TEXT = "text"
    MYSQL = "mysql"

class QueryStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    SYNTAX_ERROR = "SYNTAX_ERROR"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    INCORRECT = "INCORRECT"
    
class ErrorType(str, Enum):
    SYNTAX_ERROR = "SYNTAX_ERROR"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    UNKNOWN_COLUMN = "UNKNOWN_COLUMN"
    UNKNOWN_TABLE = "UNKNOWN_TABLE"
    AMBIGUOUS_COLUMN = "AMBIGUOUS_COLUMN"
    BAD_JOIN = "BAD_JOIN"
    AGGREGATION_ERROR = "AGGREGATION_ERROR"
    FILTER_ERROR = "FILTER_ERROR"
    PROJECTION_ERROR = "PROJECTION_ERROR"
    GENERIC_RUNTIME_ERROR = "GENERIC_RUNTIME_ERROR"
    SEMANTIC_ERROR = "SEMANTIC_ERROR"
    SCHEMA_ERROR = "SCHEMA_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

class KnowledgeScope(str, Enum):
    SYNTAX = "SYNTAX"
    STRUCTURAL = "STRUCTURAL"
    SCHEMA_SPECIFIC = "SCHEMA_SPECIFIC"

class FeedbackStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    CORRECT = "CORRECT"
    INCORRECT = "INCORRECT"
    RUNTIME_ERROR = "RUNTIME_ERROR" 